var data = {
    "shirts":[
        {
            "color": 'white',
            "band": 'Circa Survive',
            "name": 'raven white',
            "price": 25,
            "discount": false,
            "image": 'images/shirt1.jpg',
        }, {
            "color": 'red',
            "band": 'Circa Survive',
            "name": 'memory heather',
            "price": 25,
            "discount": '20% off',
            "image": 'images/shirt2.jpg',
        }, {
            "color": 'black',
            "band": 'Dance Gavin Dance',
            "name": 'pitbull',
            "price": 20,
            "discount": false,
            "image": 'images/shirt3.jpg',
        }, {
            "color": 'red',
            "band": 'Dance Gavin Dance',
            "name": 'shark attack',
            "price": 20,
            "discount": false,
            "image": 'images/shirt4.jpg',
        }, {
            "color": 'red',
            "band": 'Minus the Bear',
            "name": 'vikings',
            "price": 30,
            "discount": false,
            "image": 'images/shirt5.jpg',
        }, {
            "color": 'blue',
            "band": 'Minus the Bear',
            "name": 'bear ride',
            "price": 25,
            "discount": false,
            "image": 'images/shirt6.jpg',
        }, {
            "color": 'balck',
            "band": 'As I Lay Dying',
            "name": 'crow\'s rose',
            "price": 20,
            "discount": '15% off',
            "image": 'images/shirt7.jpg',
        }, {
            "color": 'black',
            "band": 'As I Lay Dying',
            "name": 'great blue',
            "price": 20,
            "discount": false,
            "image": 'images/shirt8.jpg',
        }, {
            "color": 'grey',
            "band": 'sound of animals',
            "name": 'bear breath',
            "price": 25,
            "discount": '20% off',
            "image": 'images/shirt9.jpg',
        }, {
            "color": 'grey',
            "band": 'Circa Survive',
            "name": 'enflamed',
            "price": 20,
            "discount": '20% off',
            "image": 'images/shirt10.jpg',
        }, {
            "color": 'black',
            "band": 'Dance Gavin Dance',
            "name": 'discover',
            "price": 25,
            "discount": false,
            "image": 'images/shirt11.jpg',
        }, {
            "color": 'grey',
            "band": 'b.t.b.a.m',
            "name": 'figure of speech',
            "price": 30,
            "discount": false,
            "image": 'images/shirt12.jpg',
        }
    ],
    hoodies:[
        {
            "color": 'black',
            "band": 'Gorod',
            "name": 'Gorod Logo',
            "price": 45,
            "discount": false,
            "image": 'images/jacket1.jpg',
        }, {
            "color": 'black',
            "band": 'Clutch',
            "name": 'The Barn',
            "price": 45,
            "discount": false,
            "image": 'images/jacket2.jpg',
        }, {
            "color": 'black',
            "band": 'Conundrum',
            "name": 'Insignia',
            "price": 50,
            "discount": '$5 off',
            "image": 'images/jacket3.jpg',
        }, {
            "color": 'grey',
            "band": 'Conundrum',
            "name": 'Branches grey',
            "price": 50,
            "discount": false,
            "image": 'images/jacket4.jpg',
        }, {
            "color": 'black',
            "band": 'Conundrum',
            "name": 'Branches black',
            "price": 50,
            "discount": false,
            "image": 'images/jacket5.jpg',
        }, {
            "color": 'Black',
            "band": 'Kronos',
            "name": 'Sythes',
            "price": 45,
            "discount": '20% off',
            "image": 'images/jacket6.jpg',
        }, {
            "color": 'black',
            "band": 'Born of Bane',
            "name": 'Skullborn',
            "price": 40,
            "discount": false,
            "image": 'images/jacket6.jpg',
        }, {
            "color": 'black',
            "band": 'WRVTH',
            "name": 'Full Haunting',
            "price": 45,
            "discount": false,
            "image": 'images/jacket8.jpg',
        }, {
            "color": 'black',
            "band": 'Behemoth',
            "name": 'Celtic Tree',
            "price": 50,
            "discount": false,
            "image": 'images/jacket9.jpg',
        }, {
            "color": 'black',
            "band": 'Escheron',
            "name": 'Escheron Logo',
            "price": 40,
            "discount": false,
            "image": 'images/jacket10.jpg',
        }, {
            "color": 'black',
            "band": 'The Agonist',
            "name": 'Desert Mirage',
            "price": 45,
            "discount": false,
            "image": 'images/jacket11.jpg',
        }, {
            "color": 'black',
            "band": 'Arktik',
            "name": 'Arktik Logo',
            "price": 45,
            "discount": '20% off',
            "image": 'images/jacket12.jpg',
        }
    ],
    headwear:[
        {
            "color": 'black',
            "band": 'Parkway Drive',
            "name": 'Palm Trees',
            "price": 15,
            "discount": false,
            "image": 'images/hat1.jpg',
        }, {
            "color": 'black',
            "band": 'Municipal Waste',
            "name": 'Yellow Logo',
            "price": 7,
            "discount": false,
            "image": 'images/hat2.jpg',
        }, {
            "color": 'black',
            "band": 'The Sword',
            "name": 'Logo Beanie',
            "price": 7,
            "discount": false,
            "image": 'images/hat3.jpg',
        }, {
            "color": 'purple',
            "band": 'Thall',
            "name": 'Logo Truckers Cap',
            "price": 15,
            "discount": false,
            "image": 'images/hat4.jpg',
        }, {
            "color": 'black',
            "band": 'Destruction',
            "name": 'Cracked Skull',
            "price": 15,
            "discount": false,
            "image": 'images/hat5.jpg',
        }, {
            "color": 'black',
            "band": 'b.t.b.a.m',
            "name": 'Falling',
            "price": 15,
            "discount": false,
            "image": 'images/hat6.jpg',
        }, {
            "color": 'black',
            "band": 'Eluveitie',
            "name": 'Logo Beanie',
            "price": 8,
            "discount": false,
            "image": 'images/hat7.jpg',
        },{
            "color": 'black',
            "band": 'Behemoth',
            "name": 'Logo Truckers Cap',
            "price": 15,
            "discount": false,
            "image": 'images/hat8.jpg',
        }, {
            "color": 'black',
            "band": 'Parkway Drive',
            "name": 'Striped Beanie',
            "price": 10,
            "discount": false,
            "image": 'images/hat9.jpg',
        }
   ]
};
